export const newFolderPlaceholderMap = {
  default: 'Enter folder name',
  ideas: [
    'Project Alpha',
    'New Folder',
    'My Documents',
    'Creative Assets',
    'Random Stuff',
    'Archive',
    'Temp Files',
    'Important',
    'Reference',
    'Personal',
    'Work Files',
    'Miscellaneous',
    'To Organize',
    'Notes',
    'Exports',
    'Backups',
    'Old Versions',
    'Final Draft',
    'Resources',
  ],
  dev: [
    'components',
    'utils',
    'hooks',
    'lib',
    'refactor-later',
    'playground',
    'tests',
    'api',
    'services',
    'types',
    'legacy',
    'src',
    'dist',
    'scripts',
  ],
  funny: [
    'Stuff I Probably Need',
    'Do Not Delete',
    'Maybe Useful',
    'No Idea What This Is',
    'Sort This Later',
    'Chaos Zone',
    'Definitely Not Important',
    'Might Be Broken',
    'Deadlines? What Deadlines?',
    'Read Me Never',
    'Delete Me Eventually',
    'WIP Forever',
  ],
};
